### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by dannywu19910524** [calclavia/DeepJ#65]
Traceback (most recent call last):
  File "generate.py", line 153, in <module>
    main()
  File "generate.py", line 142, in main
    models = build_or_load()
  File "/data/python/DeepJ-icsc/util.py", line 15, in build_or_load
    models = build_models()
  File "/data/python/DeepJ-icsc/model.py", line 149, in build_models
    notes_out = naxis(time_out, chosen, style)
  File "/data/python/DeepJ-icsc/model.py", line 111, in f
    dense_layer_cache[l] = Dense(int(x.get_shape()[3]))
TypeError: __int__ returned non-int (type NoneType)

run generate.py in CentOS 7.2, tensorflow cpu mode, python 3.5

**Comment by calclavia** [comment]
See https://github.com/calclavia/DeepJ/issues/61
