### ISSUE TITLE
write midi file error

### ISSUE THREAD

**Issue by dannywu19910524** [calclavia/DeepJ#66]
```
Writing file out/samples/output_0.mid
Traceback (most recent call last):
  File "generate.py", line 153, in <module>
    main()
  File "generate.py", line 150, in main
    write_file('output', generate(models, args.bars, styles))
  File "generate.py", line 134, in write_file
    midi.write_midifile(fpath, mf)
  File "/usr/local/python3/lib/python3.5/site-packages/midi/fileio.py", line 169, in write_midifile
    return write_midifile(out,pattern)
  File "/usr/local/python3/lib/python3.5/site-packages/midi/fileio.py", line 171, in write_midifile
    return writer.write(pattern)
  File "/usr/local/python3/lib/python3.5/site-packages/midi/fileio.py", line 105, in write
    self.write_track(track)
  File "/usr/local/python3/lib/python3.5/site-packages/midi/fileio.py", line 122, in write_track
    buf.extend(self.encode_midi_event(event))
  File "/usr/local/python3/lib/python3.5/site-packages/midi/fileio.py", line 161, in encode_midi_event
    ret.extend(event.data)
ValueError: byte must be in range(0, 256)
```

**Comment by dannywu19910524** [comment]
not every time, but very often

python3.5, tensorflow-gpu 1.2

**Comment by dannywu19910524** [comment]
i didn't load model correctly, maybe it cause this error, pls close this issue


by the way, can you tell me how to select or produce training data? @calclavia

**Comment by calclavia** [comment]
We should have referred to our dataset in our paper.

**Comment by KDcx35** [comment]
> i didn't load model correctly, maybe it cause this error, pls close this issue
> 
> by the way, can you tell me how to select or produce training data? @calclavia

i have met the same problem, so how to correctly load the model? Thank you!
