### ISSUE TITLE
Help needed : Getting error TypeError: __int__ returned non-int (type NoneType) when calling train.py

### ISSUE THREAD

**Issue by swarna-a-26** [calclavia/DeepJ#67]
I am on MAC OS X 10.3.1
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    main()
  File "train.py", line 15, in main
    models = build_or_load()
  File "/Users/swarnaananthan/storycircles/ai_music/DeepJ/util.py", line 15, in build_or_load
    models = build_models()
  File "/Users/swarnaananthan/storycircles/ai_music/DeepJ/model.py", line 149, in build_models
    notes_out = naxis(time_out, chosen, style)
  File "/Users/swarnaananthan/storycircles/ai_music/DeepJ/model.py", line 111, in f
    dense_layer_cache[l] = Dense(int(x.get_shape()[3]))
TypeError: __int__ returned non-int (type NoneType)

Please help me in fixing the issue.

**Comment by calclavia** [comment]
https://github.com/calclavia/DeepJ/issues/61
