### ISSUE TITLE
Unable to execute with any TF/Keras combination (wt/wo GPU)

### ISSUE THREAD

**Issue by slave2sync** [calclavia/DeepJ#69]
Hello,

I've tried running this model with TF 1.6 /1.4 /1.2 (with and without GPU) and Keras 2.0 and am getting the stack trace below [ubuntu 16.04, python3.6, data folder with examples] when i execute the train.py script

Unable to load model from file.
Loading data
Training
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    main()
  File "train.py", line 16, in main
    train(models)
  File "train.py", line 29, in train
    models[0].fit(train_data, train_labels, epochs=1000, callbacks=cbs, batch_size=BATCH_SIZE)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1405, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1295, in _standardize_user_data
    exception_prefix='model input')
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 121, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking model input: expected input_1 to have 4 dimensions, but got array with shape (0, 1)

I tried downgrading Keras to 1.xx but the code uses Keras 2.0 syntax.
can you please look into it?

**Comment by slave2sync** [comment]
Closed issue, was not using master branch....

**Comment by buzem** [comment]
I didn't understand how did you solve it?Could you please explain it?

**Comment by KDcx35** [comment]
i have the same problem, how you solve this?
